import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import {
  TILED_CLI_ENV,
  TILED_CLI_PATH,
  hasTiledCli,
} from "./support/tiledCli.js";

const execFileAsync = promisify(execFile);

/**
 * Why official AutoMapping is out of scope, kept as an executable fact.
 *
 * Tiled 1.12.2 offers exactly two ways to get a `TileMap` inside
 * `--evaluate`, and each fails a different precondition of
 * `EditableMap::autoMap` (src/tiled/editablemap.cpp):
 *
 *   - `tiled.open()` creates the `MapDocument` that AutoMapping needs,
 *     but throws "Editor not available" without the GUI.
 *   - `MapFormat.read()` works headlessly but returns a *detached* map,
 *     and `autoMap()` throws "AutoMapping is currently not supported for
 *     detached maps".
 *
 * This test asserts both failures still hold. When either probe starts
 * succeeding, upstream has lifted the restriction: fail loudly so the
 * out-of-scope decision in docs/02-mcp-spec.md §10 gets revisited rather
 * than silently staying stale. `--evaluate` exits 0 even when the script
 * throws, so the verdict is read from stdout markers, and the assertions
 * bind to the markers rather than Tiled's error wording so an upstream
 * rephrasing does not fire the canary.
 */

// 32x16 PNG, two 16x16 tiles. Generated bytes are embedded because
// node:zlib only grew crc32() after the Node 20 floor this repo supports.
const TILES_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAACAAAAAQCAIAAAD4YuoOAAAAIklEQVR4nGM4YGBAEjIIOEASYhi1YNSCUQtGLRi1YChYAABx4GAfbWk0ugAAAABJRU5ErkJggg==";

const TILESET = {
  columns: 2,
  image: "tiles.png",
  imageheight: 16,
  imagewidth: 32,
  margin: 0,
  name: "tiles",
  spacing: 0,
  tilecount: 2,
  tiledversion: "1.12.2",
  tileheight: 16,
  tilewidth: 16,
  type: "tileset",
  version: "1.10",
};

function tileLayer(
  name: string,
  size: number,
  data: number[],
  id: number,
): object {
  return {
    data,
    height: size,
    id,
    name,
    opacity: 1,
    type: "tilelayer",
    visible: true,
    width: size,
    x: 0,
    y: 0,
  };
}

function mapDocument(
  size: number,
  layers: object[],
): object {
  return {
    compressionlevel: -1,
    height: size,
    infinite: false,
    layers,
    nextlayerid: layers.length + 1,
    nextobjectid: 1,
    orientation: "orthogonal",
    renderorder: "right-down",
    tiledversion: "1.12.2",
    tileheight: 16,
    tilesets: [{ firstgid: 1, source: "tiles.tsj" }],
    tilewidth: 16,
    type: "map",
    version: "1.10",
    width: size,
  };
}

const CANARY_SCRIPT = `
const args = tiled.scriptArguments;
try {
  tiled.open(args[0]);
  tiled.log("CANARY_OPEN_OK");
} catch (error) {
  tiled.log("CANARY_OPEN_ERR: " + error);
}
try {
  const format = tiled.mapFormat("json");
  const map = format.read(args[0]);
  map.autoMap(args[1]);
  tiled.log("CANARY_AUTOMAP_OK");
} catch (error) {
  tiled.log("CANARY_AUTOMAP_ERR: " + error);
}
`;

describe("headless AutoMapping canary", () => {
  let root = "";

  beforeAll(async () => {
    root = await mkdtemp(
      join(tmpdir(), "tiledmcp-automap-canary-"),
    );
    await writeFile(
      join(root, "tiles.png"),
      Buffer.from(TILES_PNG_BASE64, "base64"),
    );
    await writeFile(
      join(root, "tiles.tsj"),
      JSON.stringify(TILESET),
    );
    await writeFile(
      join(root, "map.tmj"),
      JSON.stringify(
        mapDocument(4, [
          tileLayer(
            "Ground",
            4,
            [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
            1,
          ),
        ]),
      ),
    );
    await writeFile(
      join(root, "rules.tmj"),
      JSON.stringify(
        mapDocument(1, [
          tileLayer("input_Ground", 1, [1], 1),
          tileLayer("output_Auto", 1, [2], 2),
        ]),
      ),
    );
    await writeFile(
      join(root, "canary.js"),
      CANARY_SCRIPT,
    );
  });

  afterAll(async () => {
    if (root) {
      await rm(root, { recursive: true, force: true });
    }
  });

  it.skipIf(!hasTiledCli)(
    "still cannot AutoMap under tiled --evaluate",
    async () => {
      const { stdout } = await execFileAsync(
        TILED_CLI_PATH,
        [
          "--evaluate",
          join(root, "canary.js"),
          join(root, "map.tmj"),
          join(root, "rules.tmj"),
        ],
        {
          env: { ...TILED_CLI_ENV },
          timeout: 30_000,
          maxBuffer: 1024 * 1024,
        },
      );

      const lifted =
        stdout.includes("CANARY_OPEN_OK") ||
        stdout.includes("CANARY_AUTOMAP_OK");
      expect(
        lifted,
        "Tiled can now AutoMap headlessly -- revisit the out-of-scope " +
          "decision in docs/02-mcp-spec.md §10 and README.md.",
      ).toBe(false);
      expect(stdout).toContain("CANARY_OPEN_ERR:");
      expect(stdout).toContain("CANARY_AUTOMAP_ERR:");
    },
  );
});
